version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookhub
      POSTGRES_PASSWORD: bookhub_pass
      POSTGRES_DB: bookhub_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bookhub
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:8
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.10.0
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "neo4j/neo4j_pass"
    volumes:
      - neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  postgres-data:
  mongo-data:
  redis-data:
  neo4j-data:
